# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'product_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'product_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  ingest_batch_date: '1900-01-01'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  +persist_docs:
    relation: true
  
  product_analytics:
    +file_format: delta
    +table_properties:
      delta.enableDeletionVectors: false
    +materialized: incremental
    +incremental_strategy: 'append'
    
    silver:
      +tags:
        - 'silver'
      +schema: 'silver'
      customers:
        +tags:
          - 'feed_customers'
    
    gold:
      +tags:
        - 'gold'
      +schema: 'gold'
      customers:
        +tags:
          - 'feed_customers'
    
    output:
      +tags:
        - 'output'
      +schema: 'output_zone'
      +submission_method: all_purpose_cluster
      +create_notebook: False
      +cluster_id:  '{{ env_var("DBT_CLUSTER_ID") }}'
      bronze:
        +tags:
            - 'output-bronze'
      silver:
        +tags:
            - 'output-silver'
      gold:
        +tags:
            - 'output-gold'
