product_analytics:
  outputs:
    dev:
      catalog: dev
      host: "{{ env_var('DBT_ENV_SECRET_HOST') }}"
      http_path: "{{ env_var('DBT_ENV_SECRET_HTTP_PATH') }}"
       ### New compute section
      compute:
        ### Name that you will use to refer to an alternate compute
       File_Generator_Compute:
          http_path: "{{ env_var('DBT_ALL_PURPOSE_CLUSTER_HTTP_PATH') }}" # Required of each alternate compute
      schema: product_analytics_default_schema
      threads: 5
      token: "{{ env_var('DBT_ENV_SECRET_TOKEN') }}"
      type: databricks
  target: dev